### ISSUE TITLE
Lab 2 - To refactor

### ISSUE THREAD

**Issue by sergiuchilat** [ManeevDumitru/POO#2]
return this.numbers.join(' '); - remove from randomiseNumber method

```
checkParity(number) {
    if (number % 2 === 0) {
      console.log('even');
      return true;
    } else {
      console.log('odd');
      return false;
    }
  }
```

checkParity(number) {
   return  number % 2 === 0
}

`writeNumbersFromInterval` -> `numbersFromInterval`

`if (this.checkParity(number) === true && bottomLine < number && number < topLine)`

`if (this.checkParity(number) && number  > bottomLine && number < topLine)`

bottomLine -> intervalStart
bottomLine -> intervalEnd

**Comment by ManeevDumitru** [comment]
LAB 2 - Refactored
